* KEYIN.H
* Key values for KEYIN() and INPUT
* Copyright (c) 1995, Ladybridge Systems, All Rights Reserved

$list off
$define CTRL.A                   1
$define CTRL.B                   2
$define CTRL.C                   3
$define CTRL.D                   4
$define CTRL.E                   5
$define CTRL.F                   6
$define CTRL.G                   7
$define CTRL.H                   8
$define K$BACKSPACE              8
$define CTRL.I                   9
$define K$TAB                    9
$define CTRL.J                  10
$define CTRL.K                  11
$define CTRL.L                  12
$define CTRL.M                  13
$define CTRL.N                  14
$define CTRL.O                  15
$define CTRL.P                  16
$define CTRL.Q                  17
$define CTRL.R                  18
$define CTRL.S                  19
$define CTRL.T                  20
$define CTRL.U                  21
$define CTRL.V                  22
$define CTRL.W                  23
$define CTRL.X                  24
$define CTRL.Y                  25
$define CTRL.Z                  26
$define K$RETURN                13
$define K$ESC                   27
$define K$CTRL.BACKSPACE       127
$define K$DEL                  127
$define K$F1                   128
$define K$F2                   129
$define K$F3                   130
$define K$F4                   131
$define K$F5                   132
$define K$F6                   133
$define K$F7                   134
$define K$F8                   135
$define K$F9                   136
$define K$F10                  137
$define K$F11                  138
$define K$F12                  139
$define K$CTRL.F1              140
$define K$CTRL.F2              141
$define K$CTRL.F3              142
$define K$CTRL.F4              143
$define K$CTRL.F5              144
$define K$CTRL.F6              145
$define K$CTRL.F7              146
$define K$CTRL.F8              147
$define K$CTRL.F9              148
$define K$CTRL.F10             149
$define K$CTRL.F11             150
$define K$CTRL.F12             151
$define K$ALT.F1               152
$define K$ALT.F2               153
$define K$ALT.F3               154
$define K$ALT.F4               155
$define K$ALT.F5               156
$define K$ALT.F6               157
$define K$ALT.F7               158
$define K$ALT.F8               159
$define K$ALT.F9               160
$define K$ALT.F10              161
$define K$ALT.F11              162
$define K$ALT.F12              163
$define K$SHIFT.F1             164
$define K$SHIFT.F2             165
$define K$SHIFT.F3             166
$define K$SHIFT.F4             167
$define K$SHIFT.F5             168
$define K$SHIFT.F6             169
$define K$SHIFT.F7             170
$define K$SHIFT.F8             171
$define K$SHIFT.F9             172
$define K$SHIFT.F10            173
$define K$SHIFT.F11            174
$define K$SHIFT.F12            175
$define K$MOUSE                200
$define K$LEFT                 203
$define K$RIGHT                204
$define K$UP                   205
$define K$DOWN                 206
$define K$PAGE.UP              207
$define K$PAGE.DOWN            208
$define K$HOME                 209
$define K$END                  210
$define K$INSERT               211
$define K$DELETE               212
$define K$CTRL.TAB             213
$define K$CTRL.PAGE.UP         214
$define K$CTRL.PAGE.DOWN       215
$define K$CTRL.HOME            216
$define K$CTRL.END             217
$define K$USER0                218
$define K$USER1                219
$define K$USER2                220
$define K$USER3                221
$define K$USER4                222
$define K$USER5                223
$define K$USER6                224
$define K$USER7                225
$define K$USER8                226
$define K$USER9                227
